server:
  port: 9025    #puerto del servicio

eureka:         #tells about the Eureka server details and its refresh time
client:
  serviceUrl:
    #defaultZone: ${EUREKA_URI:http://service-discovery:8761/eureka}
    defaultZone: ${EUREKA_URI:http://localhost:9026/eureka}
    healthcheck:
      enabled: true

spring:
  application:
    name: Order-SPM   #nombre del servicio a usar por el servidor EUREKA
  data:
    mongodb:
      database: order-service_db-SPM
      port: 27017
