server:
  port: 8095    #puerto del servicio


spring:
  application:
    name: servicio-pedidos   #nombre del servicio a usar por el servidor EUREKA
  data:
    mongodb:
      database: servicio-pedidos_db
      port: 27017
