server:
  port: 9025    #puerto del servicio


spring:
  application:
    name: Order-SPM   #nombre del servicio a usar por el servidor EUREKA
  data:
    mongodb:
      database: servicio-pedidos_db
      port: 27017
