server:
 port: 9024    #Puerto por defecto

spring:
 application:
   name: product-SPM   #Nombre del servicio actual para ser usado por EUREKA.
 main:
   allow-bean-definition-overriding: true
 data:
   mongodb:
     database: product-service_db-SPM
     port: 27017
