server:
 port: 9024    #Puerto por defecto
 
eureka:         #tells about the Eureka server details and its refresh time
client:
  serviceUrl:
    #defaultZone: ${EUREKA_URI:http://service-discovery:8761/eureka}
    defaultZone: ${EUREKA_URI:http://localhost:9026/eureka}
    healthcheck:
      enabled: true

spring:
 application:
   name: product-SPM   #Nombre del servicio actual para ser usado por EUREKA.
 main:
   allow-bean-definition-overriding: true
 data:
   mongodb:
     database: product-service_db-SPM
     port: 27017
